# Generated by Django 3.2.9 on 2022-01-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_alter_doctors_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50)),
                ('comment_title', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_image', models.FileField(blank=True, upload_to='')),
                ('about', models.TextField(max_length=500)),
                ('departmant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentapp.departmant')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='departmant',
        ),
        migrations.DeleteModel(
            name='DoctorDetail',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.AddField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentapp.doctor'),
        ),
    ]
