# Generated by Django 3.2.9 on 2022-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='uni_shortcut',
            field=models.CharField(default='zaa', max_length=10),
        ),
    ]
