# Generated by Django 3.2.9 on 2022-01-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_bio', models.TextField(max_length=1000)),
                ('doctor_pp', models.ImageField(null=True, upload_to='uploads/')),
                ('uni_shortcut', models.CharField(max_length=10)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.depart')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50)),
                ('comment_title', models.CharField(max_length=100)),
                ('comment_body', models.TextField(max_length=1000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.doctor')),
            ],
        ),
    ]
