# Generated by Django 3.2.9 on 2022-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depart',
            name='uni_shortcut',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='uni_shortcut',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='uni_shortcut',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_pp',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
