# Generated by Django 3.2.9 on 2022-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20220124_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='uni_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
