# Generated by Django 3.2.9 on 2022-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_uni_uni_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
    ]
