# Generated by Django 3.2.9 on 2022-02-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20220202_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
