# Generated by Django 3.2.9 on 2022-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - cok kotu'), (2, '2 - kotu'), (3, '3 - orta'), (4, '4 - iyi'), (5, '5 - cok iyi')], null=True),
        ),
    ]
