# Generated by Django 3.2.9 on 2022-02-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_commentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentanswer',
            old_name='Comment',
            new_name='comment',
        ),
    ]
