# Generated by Django 3.2.9 on 2022-02-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_rename_comment_commentanswer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(choices=[(1.0, '1 - cok kotu'), (2.0, '2 - kotu'), (3.0, '3 - orta'), (4.0, '4 - iyi'), (5.0, '5 - cok iyi')], default=0),
        ),
    ]
