# Generated by Django 3.2.9 on 2022-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0014_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
