# Generated by Django 3.2.9 on 2022-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0015_doctor_doctor_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
