# Generated by Django 3.2.9 on 2022-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0017_auto_20220218_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikes',
            name='like_author',
            field=models.CharField(default='ben', max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='commentanswer',
            name='answer_author',
            field=models.CharField(max_length=150),
        ),
    ]
