# Generated by Django 3.2.9 on 2022-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0018_auto_20220218_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='like_author',
            field=models.CharField(max_length=150),
        ),
    ]
