# Generated by Django 3.2.9 on 2022-02-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0019_alter_commentlikes_like_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='likes',
        ),
    ]
