# Generated by Django 3.2.9 on 2022-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0021_commentlikes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='likes',
        ),
    ]
