# Generated by Django 3.2.9 on 2022-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0022_remove_commentlikes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
