# Generated by Django 3.2.9 on 2022-02-18 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0023_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='doc_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
    ]
