# Generated by Django 3.2.9 on 2022-02-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0025_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanswer',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comment.doctor'),
        ),
    ]
