# Generated by Django 3.2.9 on 2022-02-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0026_commentanswer_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentanswer',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.doctor'),
        ),
    ]
