# Generated by Django 3.2.9 on 2022-02-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0027_alter_commentanswer_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentanswer',
            name='doctor',
        ),
    ]
