# Generated by Django 3.2.9 on 2022-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0030_auto_20220222_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
