# Generated by Django 3.2.9 on 2022-02-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0031_comment_total_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='total_like',
            new_name='total_likes',
        ),
    ]
