# Generated by Django 3.2.9 on 2022-02-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0033_auto_20220222_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
