# Generated by Django 3.2.9 on 2022-02-23 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0035_comment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanswer',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
