# Generated by Django 3.2.9 on 2022-02-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0036_commentanswer_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='net_like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
