# Generated by Django 3.2.9 on 2022-02-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0039_comment_net_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='depart_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='uni',
            name='uni_name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_author', models.CharField(max_length=150)),
                ('answer_body', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
            ],
        ),
    ]
