# Generated by Django 3.2.9 on 2022-02-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0041_rename_answer_body_reportcomment_report_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='scholar_link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
