# Generated by Django 3.2.9 on 2022-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0042_auto_20220228_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attandance',
            field=models.CharField(blank=True, choices=[('E', 'Zorunlu'), ('H', 'Zorunlu Degil')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='grade',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='online_class',
            field=models.CharField(blank=True, choices=[('H', 'Yuzyuze Egitim'), ('E', 'Online Egitim'), ('EH', 'Hibrit Egitim')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='take_again',
            field=models.CharField(blank=True, choices=[('E', 'Evet'), ('H', 'Hayir'), ('EH', 'Emin Degilim')], max_length=2, null=True),
        ),
    ]
