# Generated by Django 3.2.9 on 2022-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0043_auto_20220228_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.CharField(blank=True, choices=[('NO', 'Henuz Bilmiyorum'), ('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], max_length=2, null=True),
        ),
    ]
