# Generated by Django 3.2.9 on 2022-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0044_alter_comment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attandance',
            field=models.CharField(blank=True, choices=[('Zorunlu', 'Zorunlu'), ('Zorunlu Degil', 'Zorunlu Degil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.CharField(blank=True, choices=[('Henuz Bilmiyorum', 'Henuz Bilmiyorum'), ('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='online_class',
            field=models.CharField(blank=True, choices=[('Yuzyuze Egitim', 'Yuzyuze Egitim'), ('Online Egitim', 'Online Egitim'), ('Hibrit Egitim', 'Hibrit Egitim')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='take_again',
            field=models.CharField(blank=True, choices=[('Evet', 'Evet'), ('Hayir', 'Hayir'), ('Emin Degilim', 'Emin Degilim')], max_length=20, null=True),
        ),
    ]
