# Generated by Django 3.2.9 on 2022-03-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0046_auto_20220228_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='scholar_link',
        ),
    ]
