# Generated by Django 3.2.9 on 2022-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0049_auto_20220302_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
