# Generated by Django 3.2.9 on 2022-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0050_alter_doctor_doctor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_av_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
