# Generated by Django 3.2.9 on 2022-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0051_doctor_doctor_av_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_total_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
