# Generated by Django 3.2.9 on 2022-03-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0052_doctor_doctor_total_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(choices=[(5.0, '5 - cok iyi'), (4.0, '4 - iyi'), (3.0, '3 - orta'), (2.0, '2 - kotu'), (1.0, '1 - cok kotu')], null=True),
        ),
    ]
