# Generated by Django 3.2.9 on 2022-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0053_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
