# Generated by Django 3.2.9 on 2022-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0055_alter_comment_comment_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
