# Generated by Django 3.2.9 on 2022-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0056_auto_20220311_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_author', models.CharField(max_length=150)),
                ('request_body', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
