# Generated by Django 4.0.3 on 2022-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0057_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author_email',
            field=models.CharField(default='default@edu.tr', max_length=150),
        ),
    ]
