# Generated by Django 4.0.3 on 2022-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0058_comment_comment_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author_email',
            field=models.CharField(max_length=150),
        ),
    ]
