# Generated by Django 4.0.3 on 2022-04-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0059_alter_comment_comment_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_pp',
        ),
    ]
