# Generated by Django 4.0.3 on 2022-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0060_remove_doctor_doctor_bio_remove_doctor_doctor_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attandance',
            field=models.CharField(blank=True, choices=[('Zorunlu', 'Zorunlu'), ('Zorunlu Değil', 'Zorunlu Değil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.CharField(blank=True, choices=[('Henüz Bilmiyorum', 'Henüz Bilmiyorum'), ('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='online_class',
            field=models.CharField(blank=True, choices=[('Yüzyüze Eğitim', 'Yüzyüze Eğitim'), ('Online Eğitim', 'Online Eğitim'), ('Hibrit Eğitim', 'Hibrit Eğitim')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(choices=[(5.0, '5 - çok iyi'), (4.0, '4 - iyi'), (3.0, '3 - orta'), (2.0, '2 - kötü'), (1.0, '1 - çok kötü')], null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='take_again',
            field=models.CharField(blank=True, choices=[('Evet', 'Evet'), ('Hayır', 'Hayır'), ('Emin Değilim', 'Emin Değilim')], max_length=20, null=True),
        ),
    ]
