# Generated by Django 4.0.3 on 2022-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0061_alter_comment_attandance_alter_comment_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_author', models.CharField(max_length=150)),
                ('uni_name', models.CharField(max_length=150)),
                ('faculty_name', models.CharField(max_length=150)),
                ('depart_name', models.CharField(max_length=150)),
                ('doctor_name', models.CharField(max_length=150)),
                ('doctor_lecture', models.CharField(max_length=150)),
            ],
        ),
    ]
